### ISSUE TITLE
Duplicate output in the "Problems" panel 

### ISSUE THREAD

**Issue by LordZane** [rust-lang/rls-vscode#133]
![untitled](https://user-images.githubusercontent.com/8398815/29647025-e29cfca4-8854-11e7-9ac8-b159998eb29a.png)

**Comment by nrc** [comment]
Was this after doing a cargo build? (I.e., with a task, rather than just the normal checks as you type). I expect in that case we might show both sources of errors.

If this is the case, we could:
* not show errors from cargo tasks (we do show the console output, or could)
* try and be clever and match errors, and elide them in this case. For now, that would be easy, but if we modify the way the RLS presents errors, the duplication would return.

**Comment by LordZane** [comment]
I think this was due to me using `unimplemented!()` and then running the `cargo run` task, as now that my program compiles, I only see the `[rustc]` errors

**Comment by kanerogers** [comment]
I am also experiencing this issue. Not a deal breaker, but it is a bit annoying.


![screen shot 2017-11-29 at 3 08 04 pm](https://user-images.githubusercontent.com/2022375/33357603-24ebaf88-d517-11e7-9f31-731d9eee7e49.png)

**Comment by Xanewok** [comment]
It happens because the plugin has a problem matcher for tasks (like `cargo run`), so these are published by the tasks but don't go away unless they disappear when running the task again, with no errors/warnings this time.
I'm somewhat torn about what to do with this. I think that since the analysis keeps getting better and supporting more use cases is on it's way, we might drop the problem matchers. They are good, however, when one doesn't want to have a constantly running background check (to save battery?) and runs cargo run from time to time himself.

**Comment by nrc** [comment]
I wonder if we could explicitly remove the errors from a task run? Either when we do the next RLS build or after five minutes or something?

**Comment by kanerogers** [comment]
I would vote for removing them when RLS is run again. What can get quite annoying is when RLS and cargo errors get out of sync.

For example: let’s say I have an error on line 5, and run `cargo build`. I then add another line, which moves the error to line 6. RLS tells me that the error is on line 6, but the stale error from the last `cargo build` erroneously tells me I have an error on line 5. I now have two errors, but one error is incorrect.

Hope this makes sense. I haven’t had any experience with vscode extensions, but I’d be happy to take a look if somebody has an idea of where to get started/how to test.

Thanks,
Kane

**Comment by Xanewok** [comment]
I'm not sure if vscode allows extensions to mess with problems reported by tasks.json. I tried to dig around the vscode codebase for that, but couldn't find an API to access/modify the problems, only to report them.

**Comment by nurpax** [comment]
Did you ever figure this one out? Could this be a fix for it: https://github.com/Microsoft/vscode-go/issues/2100

**Comment by Xanewok** [comment]
A cursory glance at the fix (https://github.com/Microsoft/vscode-go/pull/2109) from the linked issue looks like it involves manually deduplicating the reported diagnostics. Might be something worth doing on our side.
