### ISSUE TITLE
Possible to use this ext where rustup/rustc/cargo is provided by WSL?

### ISSUE THREAD

**Issue by kardeiz** [rust-lang/rls-vscode#144]
Is it possible to use this extension on Windows, where VSCode is a Windows app, but where `rustup`/`rustc`/`cargo`/`rls` are provided through the Windows Subsystem for Linux (WSL) `bash`?

I've tried some naive things, like changing the integrated terminal and `windowsExec` to use `bash`, which works just fine, but the plugin keeps complaining "Couldn't start client Rust Language Server".

I also tried hardcoding `rls.path` to the path of RLS (installed via rustup on WSL bash).

Thanks!

**Comment by Xanewok** [comment]
Hm, piping stdio/stdout `bash -c '<cmd>'` does seem to work as per [Windows Interoperability](https://msdn.microsoft.com/en-us/commandline/wsl/interop).

I believe https://github.com/Microsoft/vscode/issues/22663 might be relevant (as it gets into internals how language server processes are spawned)? I believe the issues it that node runtime in VSCode spawns processes naively using the same subsystem, which might be causing problems. It seems someone posted a workaround, could you try and see if it works?

**Comment by kardeiz** [comment]
Sorry, I just gave up on this for a while. If you are referring to the `wsl-bash-tools` wrapper mentioned in that thread, I tried that, but it doesn't work (and possibly doesn't quite address the issue of child process forking? This is mostly over my head).

I just discovered that it's possible to view the Chrome dev console in VSCode, which was a huge help. 

I see in the warnings:

```
Error: Error running `rustc`: Error: spawnSync C:\Users\me\vscode_ext\wsl-bash-tools-master\wsl-bash-run.bat /home/me/.cargo/bin/rustup ENOENT
	at getSysroot
```

Then I see:

```
running C:\Users\me\vscode_ext\wsl-bash-tools-master\wsl-bash-run.bat /home/me/.cargo/bin/rls
```

And no further errors or output, although the extension host crashes 30 seconds or so later.

Any thoughts?

**Comment by jonasbb** [comment]
Just an idea to establish connection between RLS and VS Code. I cannot test this as I don't use Windows. Can you run

    nc -kl `which rls` 1234

in WSL. Under Windows you would then create a cmd file containing the equivalent of `nc localhost 1234` and configure VS Code by setting the `rls.path` configuration to this cmd script.

Although, I am not sure if using RLS this way would work, even if the communication works. The reason is that RLS needs access to the files in the cargo project using the paths provided by the LSP client. Since the LSP client (VS Code) would use Windows paths but RLS would expect Linux paths this might be a problem.

The LSP (language server protocol) does not offer using a "remote" server in all cases, e.g., the LSP does not provide a way for the server to access files through the client. It would require a custom LSP extension to make this work. This also means that sandboxing LSP servers or running them on a remote machine is not simple.

**Comment by kardeiz** [comment]
I'm not sure exactly what that command is trying to do. `which rls` just outputs the path to rls, which is not a valid hostname.

Also, as far as I can tell, RLS does not run as an HTTP service, but rather as some kind of stdio loop service (not sure what to call this).

In any case, the output of that command in WSL is basically the same as it is on my CentOS box:

    nc: getaddrinfo: Name or service not known

**Comment by jonasbb** [comment]
@kardeiz I forgot the `-e` parameter at first, Did you use that? The idea is just to pipe the stdio stuff through TCP to WSL, assuming TCP will work better than stdio.

The command should open netcat listening on port 1234 on localhost and execute rls (`-e`).

**Comment by donaldpipowitch** [comment]
Hi, I'm quite new to the WSL. I'm not sure what "containing the equivalent of nc localhost 1234" should look like 🤔 Can someone explain this to me? Or is there an even better way to solve this available now?

Thank you.

**Comment by newtack** [comment]
Any update on whether we can use WSL?

**Comment by yisonPylkita** [comment]
@newtack There is a problem with filesystem paths mapping so you need to wait for GH-335

**Comment by yisonPylkita** [comment]
Since https://github.com/rust-lang/rls-vscode/pull/488 was merged `rls-vscode` supports running `vscode` on Windows and `rust`, `cargo`, `rustup`.. on WSL.

@Xanewok Issue can be closed

**Comment by Xanewok** [comment]
Will do that, thanks for doing the triage!
