### ISSUE TITLE
Factor out a SessionManager singleton

### ISSUE THREAD

**Issue by nrc** [rust-lang/rls-vscode#152]
See https://github.com/rust-lang-nursery/rls-vscode/pull/150#issuecomment-330765229 #150 introduced an `lc` global, it would be nice to factor that and other bits of client state into a class.

**Comment by genneth** [comment]
Just jotting down what I understand of the structure from browsing through [vscode-powershell](https://github.com/PowerShell/vscode-powershell):
 * `SessionManager` controls server and client startup, as well as config changes --- all controlled via restarting the session. Since things like `registerCommand` are one-off, some actions need to be done once in the constructor, and some things can't be done at all without forcing a restart of VS Code.
 * `IFeatures` implement orthogonal functionalities to do with communicating with the language server. Again, each feature can register their own commands in the constructor. Sometimes even registration needs the server and this can be worked around by essentially waiting for the language client to start.
 * For some reason that I don't really understand, they don't use `ExtensionContext.subscriptions` to dispose of things, preferring to manage lifetimes explicitly everywhere. It certainly makes it clearer during restart sequences whether everything was properly disposed, but probably runs some risk of forgetting?

**Comment by genneth** [comment]
Having thought about this, I'm not entirely sure it's actually that great an idea, unless the extension were to get very complex, such as if RLS picks up quite a few more custom features which needed non-trivial user interaction to deal with. Perhaps a better intermediate goal would be to make certain config changes automatically trigger/ask the user for reloading the server. If in the course of that, it starts looking kinda hairy, then it would justify the refactoring.

**Comment by Xanewok** [comment]
We effectively did that as part of multi-root workspace support - each folder has its own instance and is responsible for the correct spawn and disposal of the registered resource. As such, I'll close this issue.
