### ISSUE TITLE
Giant fonts mess up popup boxes

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rls-vscode#213]
I just installed and tryed using Rust via rls-vscode in Visual Studio Code.
So far I really liked it but the screenshot tells it all ...

Some additional information if it might help:
I am working on Archlinux 64-bit, i3 tiling window manager, Rust nightly channel, RLS downloaded and installed by the plugin.

![Screenshot](https://i.imgur.com/W6exrqH.png)

**Note:** This does not happen for all popup boxes but just for some.

**Comment by nrc** [comment]
I wonder if there is markdown from rustdoc in the doc comment which we are rendering?

**Comment by Robbepop** [comment]
The source code origin of this visual glitch is [here](https://github.com/Robbepop/apint/blob/master/src/apint/relational.rs#L102) pointing to the method `with_annotation` in [this](https://github.com/Robbepop/apint/blob/master/src/errors.rs#L103) source location of the same project.

Maybe it helps. :)

**Comment by Xanewok** [comment]
The offending doc comments are:
```rust
// ===========================================================================
///  Extending constructors for `Error`.
/// ===========================================================================
```
The first line has `//` to cleverly omit the "=====(...)" from the hover tooltip, however the
```markdown
Heading
=====
```
is a valid Markdown syntax and it's syntactically equivalent to
```md
# Heading
```
which makes it render the entire line as H1 header (enormous!) by the VSCode.

The overlap is more of a VSCode bug; to work around it and retain the Visual * 2005 style comments you should just use the regular `//` comments (especially since these effectively comment a region of code and not a single Rust item).
