### ISSUE TITLE
Incorrectly reports missing Cargo.toml if it's not in the root

### ISSUE THREAD

**Issue by chriskrycho** [rust-lang/rls-vscode#222]
I'm working on a small multi-lang project where the `Cargo.toml` is in a child of the root directory:

```
root/
  README.md
  rust/
    cargo.toml
  # other stuff
```

It incorrectly reports that:

> Cargo.toml must be in the workspace in order to support all features

Of course, `Cargo.toml` *is* in the workspace…

![code-error](https://user-images.githubusercontent.com/2403023/34464958-a61eb540-ee54-11e7-8356-d816fb6a244b.png)

**Comment by jeffryang24** [comment]
Yes... It also happens to me...

**Comment by maelvalais** [comment]
I think the error message has been changed to 

    A Cargo.toml file must be at the root of the workspace in order to support all features

meaning that rls-vscode expects cargo.toml to be at the root of your workspace. Sadly, this implies we have to find a workaround for multi-lang projects (for example, use the "Add folder to workspace" feature in vscode) 🤔

**Comment by maelvalais** [comment]
I perused some of the extension's code but could not find how to hack it so that the 'root_path' for Cargo.toml is different from `workspace.rootPath`. That said, I found out that https://github.com/rust-lang-nursery/rls-vscode/commit/333332309695bb94e6d4e8c882db669d2b50d65f removed the variable `rls.root` that allowed running the rust language server from a different directory.

The commit message says: 
> rls.path is a better option, we don't need two ways and I don't think anyone uses this one any more

Maybe we need it back? 😊

**Comment by enioluwa23** [comment]
Yup! Seems like that's it. Especially with neon/ffi-like modules I think people would like this customized instead of having two VS Code workspaces open at the same time to have rls functionality.

**Comment by joseluisq** [comment]
Any progress on this feature?

**Comment by jannickj** [comment]
This issue is really annoying when working with a rust, rarely is rust my sole project. 
@maelvalais Solutions seems like a nice hack, but it doesn't fix the problem if you have multiple rust projects at the same time. What we actually need is for the extension to find the cargo.toml based on the file you have active and then either reuse or spin up a new language server.

**Comment by maelvalais** [comment]
You are right, my hack does not really help in these scenarios. Let us imagine we have open vscode in an hypothetical `project/` folder that contains multiple rust projects (each one with a `Cargo.toml` and `src/*.rs`):

```
project/
├── lib1/
│  ├── Cargo.toml
│  └── src/
│     └── main1.rs
├── lib2/
│  ├── Cargo.toml
│  └── src/
│     └── main2.rs
└── lib3/
   ├── Cargo.toml
   └── src/
      └── main3.rs
```

Now, let's imagine a scenario:

1. open the `project/` in vscode
2. **open file `main1.rs`**
3. the extension fires up and looks for `Cargo.toml` in the parent folder and finds `lib1/Cargo.toml`
4. the Cargo.toml is found: the extension creates a new rls instance
5. **now, open file `main2.rs`**
6. the extension notices this file isn't related to the previous `Cargo.toml` from `lib1/`
7. the extension looks for a `Cargo.toml` in the parent folder and finds `lib2/Cargo.toml`
8. the extension creates a second rls instance (but the other one is still running)

@jannickj Does this scenario fits your description of the way you expect the extension to operate?

**Comment by jannickj** [comment]
@maelvalais  yes that's exactly how I would love it to operate :)

**Comment by jannickj** [comment]
#457 implements what @maelvalais proposed

**Comment by jannickj** [comment]
@nrc, I'm really looking forward to having this feature, do you know when you have time to look at it?
