### ISSUE TITLE
vscode terminal: Jump to source line on error and warning.

### ISSUE THREAD

**Issue by robertlugg** [rust-lang/rls-vscode#387]
When I run from VSCode's Integrated Terminal and get an error or warning, I'd like to be able to simply move to the file and line:column.  Turning the file:line:column text into a hyperlink seems ideal although I don't know how technically difficult it is.

Example 1: Warning:
```
warning: field is never used: `query`
--> **src\main.rs:7:5**
```
Example 2: Error:
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', **src\main.rs:15:20**
```

**Comment by radu-matei** [comment]
Hi!
I don't think this is specific to the Rust extension -- you can Ctrl/Cmd + click on the file and VS Code will open it, at the correct line and column.

I'd be curious if this is an issue with the version of the tooling you were running here (mainly how it outputs the location of an error / warning), because you can literally echo in your terminal a file with line and column, and VS Code creates a link to the file, if it's in the workspace:

<img width="456" alt="Screen Shot 2019-03-30 at 11 58 22" src="https://user-images.githubusercontent.com/13103165/55274665-4cbcb480-52e3-11e9-94f4-ee523876157e.png">

Also, current versions of `cargo` output the location in a way that VS Code can create links:

<img width="331" alt="Screen Shot 2019-03-30 at 12 00 48" src="https://user-images.githubusercontent.com/13103165/55274681-868dbb00-52e3-11e9-9f04-0dd40571dfa7.png">

**Comment by Xanewok** [comment]
This should working as per comment above, so I'm closing the issue. Please reopen if you still have problems!
