### ISSUE TITLE
Could not find 'Cargo.toml' in 'C:\Users\...\Documents'

### ISSUE THREAD

**Issue by Tape-Worm** [rust-lang/rls-vscode#406]
I decided to play around with Rust last night (never used it before).  So I got everything set up:

- Rustup
- RLS
- VisualStudio Code (1.26.1)
- This plug in/extension

I'm able to debug and run my application fine, but when I try to check or build the application I get this:
![image](https://user-images.githubusercontent.com/9710137/44553787-e25bea00-a6eb-11e8-89fb-6e58e74831ad.png)

I have no idea why this is happening.  I haven't done anything special... at least I don't think.  Not sure if this is your issue or vscode.  But I figured I'd try here first.

Here's my project setup:
![image](https://user-images.githubusercontent.com/9710137/44553843-19320000-a6ec-11e8-90fd-e4d30a76461e.png)
For reference, the project is located at "D:\Code\RustTest\"

It should be able to find the Cargo.toml right?

**Comment by nrc** [comment]
Was `D:\Code\RustTest` the directory you opened in VSCode? And is that the directory with Cargo.toml in it?

It looks like something (Cargo, probably) is looking for Cargo.toml in your documents directory, I'm not sure why.

**Comment by Tape-Worm** [comment]
Sorry for the delay, but the answer to your questions is: Yes and yes.

**Comment by mrdrbob** [comment]
I was having the same problem.  In my case, the issue was in my Powershell profile, where I had a line that set the current path (so when I open Powershell, it opens in a more convenient directory).  VSCode apparently runs your profile script when it opens a terminal, which explains why it couldn't find the Cargo.toml file.  When I removed the `Set-Location ...` line from my `Microsoft.PowerShell_profile.ps1` file, the build commands started working.

**Comment by Tape-Worm** [comment]
Well, I had totally forgotten about this until a coworker and I were talking about Rust.  And I went back to see if my profile script had a directory change in it, and sure enough, it did.

Removing that fixed it.  

Question is, is this a vs code problem? or a problem with the plug in?

Anyway, it works now, so I guess this can be closed.
