### ISSUE TITLE
Unknown RLS configuration: `trace` 

### ISSUE THREAD

**Issue by albertosantini** [rust-lang/rls-vscode#530]
Any hint if I get that message when I open the project with `Rust (rls) 0.5.4`?

```
$ cargo --version
cargo 1.35.0-nightly (0e35bd8af 2019-03-13)
$ rustc --version
rustc 1.35.0-nightly (bc44841ad 2019-03-14)
$ rls --version
rls 1.34.0 (6840dd6 2019-03-10)
$

**Comment by galich** [comment]
same here, i think it breaks Go to Reference, Find All References and error highlights

**Comment by ImScottIRL** [comment]
Looks like this is the cause:
https://github.com/rust-lang/rls-vscode/commit/111e12cded13270e01b187ee5d39b5d6c4853868

Perhaps I've got to use a specific version of rls? I'm using 1.34.0.

**Comment by Xanewok** [comment]
Currently, the LSP client sends everything that's prefixed with "rust.*" to the server as the configuration. We could either temporarily special use (or even use somehow?) the "rust.trace" option inside the RLS or change the way the configuration is handled in the extension; currently it's push-based but it seems that the vscode LSP devs changed it in the 5.1 version (https://github.com/Microsoft/vscode-languageserver-node/commit/621b6519b2f3e6153d331aeddf544b6de3ca814c)

**Comment by ppiet** [comment]
Thanks for the context, @Xanewok ! Why does rls-vscode set `rust.trace` in `package.json` ( 111e12c ) if RLS is not using/recognizing it? Is it a version mismatch problem?

**Comment by Acidic9** [comment]
This problem is really casuing me issues - Any quick fix for now?

**Comment by TheGoddessInari** [comment]
I haven't looked too hard into this, as a disclaimer.

I suppose the quick fix would be to remove the offending lines from package.json and package it yourself with vsce, and install from the VSIX.

The problem seems to be that the language server requires the `rust.trace.server` part to be based on the language id (`rust`), while that's passing everything to the language server, and the other rls-vscode specific bits use `rust-client.*` instead.
