### ISSUE TITLE
RLS build all the file

### ISSUE THREAD

**Issue by cylof22** [rust-lang/rls-vscode#592]
When a file is changed, all the files of the same project will be compiled. Is there an option to compile only the changed file?

**Comment by CptFox** [comment]
That's due to the fact that unlike C/C++, where the translation unit is the file, Rust's translation unit is the crate.

If you want incremental compiling within your project, you'll need to split it in subcrates. As a plus, it carries over to cargo incremental compilation.

You can have your main Cargo.toml reference them using stuff like this: `subcrate = {version="", path="relative/path/to/subcrate"}`.

Just use `cargo new --lib subcrate` to generate the file structure.

**Comment by Xanewok** [comment]
That's a very good explanation, thank you @CptFox =) I'll close this issue as resolved then.
